In [1]:
'''
Calculate the distance traveled and days on the road for each team over the entire season
schedule
'''
import pandas as pd
import numpy as np
import datetime

season_str = '2025-26'
#cutoff_date = datetime.datetime.now()
cutoff_date = pd.to_datetime('2025-11-26')

##### importing custom modules from the projects folder
import sys
from pathlib import Path
# Start at current working directory
current = Path.cwd()
# Walk up the tree until config.py is found or root is reached
for parent in [current] + list(current.parents):
    config_path = parent / "config.py"
    if config_path.exists():
        sys.path.append(str(parent))
        import config # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 
        break
else:
    raise FileNotFoundError("config.py not found in any parent directories")

import scripts.functions.NBAteamSeasonTravel as travel

In [3]:
traveler = travel.seasonTeamTravelDistanceCalculator()
traveler.get_arena_distances()
traveler.get_season_schedule(season_str=season_str)

In [5]:
traveler.process_schedule(cutoff_date = cutoff_date)
sched = traveler.schedules['processed']['2025-26']
sched.round(0)

,gameId,gameDate,team,opp,home,is_b2b,prev_home,next_home,days_rest,distance_miles,...,days_since_last_game,prev_opp,arena_from,arena_to,homeTeam_teamName,awayTeam_teamName,homeTeam_teamId,awayTeam_teamId,teamId,oppId
0,0022500082,2025-10-22,Hawks,Raptors,True,False,True,False,NaN,0.0,...,NaN,0,1610612737,1610612737,Hawks,Raptors,1610612737,1610612761,1610612737,1610612761
1,0022500090,2025-10-24,Hawks,Magic,False,False,True,True,1.0,402.0,...,2.0,1610612761,1610612737,1610612753,Magic,Hawks,1610612753,1610612737,1610612737,1610612753
2,0022500101,2025-10-25,Hawks,Thunder,True,True,False,False,0.0,402.0,...,1.0,1610612753,1610612753,1610612737,Hawks,Thunder,1610612737,1610612760,1610612737,1610612760
3,0022500115,2025-10-27,Hawks,Bulls,False,False,True,False,1.0,589.0,...,2.0,1610612760,1610612737,1610612741,Bulls,Hawks,1610612741,1610612737,1610612737,1610612741
4,0022500130,2025-10-29,Hawks,Nets,False,False,False,False,1.0,715.0,...,2.0,1610612741,1610612741,1610612751,Nets,Hawks,1610612751,1610612737,1610612737,1610612751
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521,0022500229,2025-11-15,Hornets,Thunder,True,True,False,False,0.0,660.0,...,1.0,1610612749,1610612749,1610612766,Hornets,Thunder,1610612766,1610612760,1610612766,1610612760
522,0022500245,2025-11-17,Hornets,Raptors,False,False,True,False,1.0,587.0,...,2.0,1610612760,1610612766,1610612761,Raptors,Hornets,1610612761,1610612766,1610612766,1610612761
523,0022500256,2025-11-19,Hornets,Pacers,False,False,False,True,1.0,440.0,...,2.0,1610612761,1610612761,1610612754,Pacers,Hornets,1610612754,1610612766,1610612766,1610612754
524,0022500268,2025-11-22,Hornets,Clippers,True,False,False,False,2.0,428.0,...,3.0,1610612754,1610612754,1610612766,Hornets,Clippers,1610612766,1610612746,1610612766,1610612746
525,0022500276,2025-11-23,Hornets,Hawks,False,True,True,NaN,0.0,227.0,...,1.0,1610612746,1610612766,1610612737,Hawks,Hornets,1610612737,1610612766,1610612766,1610612737

In [18]:
import nba_api.stats.endpoints as n

In [25]:
box = n.boxscoretraditionalv3.BoxScoreTraditionalV3(game_id='0022500090')
df_box = box.player_stats.get_data_frame()
df_box

,gameId,teamId,teamCity,teamName,teamTricode,teamSlug,personId,firstName,familyName,nameI,...,reboundsOffensive,reboundsDefensive,reboundsTotal,assists,steals,blocks,turnovers,foulsPersonal,points,plusMinusPoints
0,0022500090,1610612737,Atlanta,Hawks,ATL,hawks,1629638,Nickeil,Alexander-Walker,N. Alexander-Walker,...,0,1,1,4,1,0,1,0,19,-1.0
1,0022500090,1610612737,Atlanta,Hawks,ATL,hawks,1630552,Jalen,Johnson,J. Johnson,...,2,6,8,1,1,0,3,5,12,-12.0
2,0022500090,1610612737,Atlanta,Hawks,ATL,hawks,1630168,Onyeka,Okongwu,O. Okongwu,...,0,4,4,3,1,3,2,5,17,-11.0
3,0022500090,1610612737,Atlanta,Hawks,ATL,hawks,1630700,Dyson,Daniels,D. Daniels,...,0,9,9,4,2,1,2,4,6,10.0
4,0022500090,1610612737,Atlanta,Hawks,ATL,hawks,1629027,Trae,Young,T. Young,...,0,1,1,6,3,0,1,0,25,8.0
5,0022500090,1610612737,Atlanta,Hawks,ATL,hawks,1631243,Mouhamed,Gueye,M. Gueye,...,4,4,8,3,0,1,3,2,13,21.0
6,0022500090,1610612737,Atlanta,Hawks,ATL,hawks,1628379,Luke,Kennard,L. Kennard,...,2,1,3,2,1,0,2,3,6,11.0
7,0022500090,1610612737,Atlanta,Hawks,ATL,hawks,1642368,N'Faly,Dante,N. Dante,...,1,2,3,0,0,0,1,0,0,1.0
8,0022500090,1610612737,Atlanta,Hawks,ATL,hawks,1630249,Vít,Krejčí,V. Krejčí,...,0,2,2,1,0,0,1,1,5,-9.0
9,0022500090,1610612737,Atlanta,Hawks,ATL,hawks,1630811,Keaton,Wallace,K. Wallace,...,0,1,1,2,0,0,0,0,3,-7.0
10,0022500090,1610612737,Atlanta,Hawks,ATL,hawks,1642854,Asa,Newell,A. Newell,...,0,0,0,0,0,0,0,1,5,9.0
11,0022500090,1610612737,Atlanta,Hawks,ATL,hawks,1631216,Caleb,Houstan,C. Houstan,...,0,0,0,0,0,0,0,0,0,0.0
12,0022500090,1610612737,Atlanta,Hawks,ATL,hawks,1631210,Jacob,Toppin,J. Toppin,...,0,0,0,0,0,0,0,0,0,0.0
13,0022500090,1610612753,Orlando,Magic,ORL,magic,1630532,Franz,Wagner,F. Wagner,...,2,4,6,2,1,0,4,5,27,-2.0
14,0022500090,1610612753,Orlando,Magic,ORL,magic,1631094,Paolo,Banchero,P. Banchero,...,0,6,6,1,0,0,3,3,11,-10.0
15,0022500090,1610612753,Orlando,Magic,ORL,magic,1628976,Wendell,Carter Jr.,W. Carter Jr.,...,3,5,8,2,2,0,2,4,10,-10.0
16,0022500090,1610612753,Orlando,Magic,ORL,magic,1630217,Desmond,Bane,D. Bane,...,2,5,7,5,0,0,3,2,15,-7.0
17,0022500090,1610612753,Orlando,Magic,ORL,magic,1630591,Jalen,Suggs,J. Suggs,...,0,3,3,4,0,0,4,4,11,4.0
18,0022500090,1610612753,Orlando,Magic,ORL,magic,1641710,Anthony,Black,A. Black,...,0,3,3,2,1,0,4,4,8,2.0
19,0022500090,1610612753,Orlando,Magic,ORL,magic,1641783,Tristan,da Silva,T. da Silva,...,3,3,6,3,3,0,1,1,15,8.0
20,0022500090,1610612753,Orlando,Magic,ORL,magic,1626145,Tyus,Jones,T. Jones,...,0,1,1,2,0,1,1,1,4,-9.0
21,0022500090,1610612753,Orlando,Magic,ORL,magic,1629048,Goga,Bitadze,G. Bitadze,...,2,3,5,0,0,2,0,2,3,6.0
22,0022500090,1610612753,Orlando,Magic,ORL,magic,1641724,Jett,Howard,J. Howard,...,0,0,0,0,0,0,0,0,3,-2.0
23,0022500090,1610612753,Orlando,Magic,ORL,magic,1628371,Jonathan,Isaac,J. Isaac,...,0,0,0,0,0,0,0,0,0,0.0
24,0022500090,1610612753,Orlando,Magic,ORL,magic,1642869,Noah,Penda,N. Penda,...,0,0,0,0,0,0,0,0,0,0.0
25,0022500090,1610612753,Orlando,Magic,ORL,magic,1642859,Jase,Richardson,J. Richardson,...,0,0,0,0,0,0,0,0,0,0.0