# current season research for daily look

In [1]:
'''
Calculate the distance traveled and days on the road for each team over the entire season
schedule
'''
import pandas as pd
import numpy as np
import datetime

season_str = '2025-26'
#cutoff_date = datetime.datetime.now()
cutoff_date = pd.to_datetime('2025-11-26')

##### importing custom modules from the projects folder
import sys
from pathlib import Path
# Start at current working directory
current = Path.cwd()
# Walk up the tree until config.py is found or root is reached
for parent in [current] + list(current.parents):
    config_path = parent / "config.py"
    if config_path.exists():
        sys.path.append(str(parent))
        import config # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 
        break
else:
    raise FileNotFoundError("config.py not found in any parent directories")

import scripts.functions.NBAteamSeasonTravel as travel


traveler = travel.seasonTeamTravelDistanceCalculator()
# access csv that has calculated distances from arena to arena
traveler.get_arena_distances()

# pull schedules for a season
traveler.get_season_schedule(
    season_str=season_str, 
    remove_gametypes = ['001', '003', '004', '005', '006']  # filters down to only regular season using ['001', '003', '004', '005', '006']. None or empty will provide full schedules
)
# process the data
traveler.process_schedule(cutoff_date = cutoff_date)
sched = traveler.schedules['processed']['2025-26']
sched.round(0)

,gameId,gameDate,team,opp,home,is_b2b,prev_home,next_home,days_rest,distance_miles,...,days_since_last_game,prev_opp,arena_from,arena_to,homeTeam_teamName,awayTeam_teamName,homeTeam_teamId,awayTeam_teamId,teamId,oppId
0,0022500082,2025-10-22,Hawks,Raptors,True,False,True,False,NaN,0.0,...,NaN,0,1610612737,1610612737,Hawks,Raptors,1610612737,1610612761,1610612737,1610612761
1,0022500090,2025-10-24,Hawks,Magic,False,False,True,True,1.0,402.0,...,2.0,1610612761,1610612737,1610612753,Magic,Hawks,1610612753,1610612737,1610612737,1610612753
2,0022500101,2025-10-25,Hawks,Thunder,True,True,False,False,0.0,402.0,...,1.0,1610612753,1610612753,1610612737,Hawks,Thunder,1610612737,1610612760,1610612737,1610612760
3,0022500115,2025-10-27,Hawks,Bulls,False,False,True,False,1.0,589.0,...,2.0,1610612760,1610612737,1610612741,Bulls,Hawks,1610612741,1610612737,1610612737,1610612741
4,0022500130,2025-10-29,Hawks,Nets,False,False,False,False,1.0,715.0,...,2.0,1610612741,1610612741,1610612751,Nets,Hawks,1610612751,1610612737,1610612737,1610612751
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521,0022500229,2025-11-15,Hornets,Thunder,True,True,False,False,0.0,660.0,...,1.0,1610612749,1610612749,1610612766,Hornets,Thunder,1610612766,1610612760,1610612766,1610612760
522,0022500245,2025-11-17,Hornets,Raptors,False,False,True,False,1.0,587.0,...,2.0,1610612760,1610612766,1610612761,Raptors,Hornets,1610612761,1610612766,1610612766,1610612761
523,0022500256,2025-11-19,Hornets,Pacers,False,False,False,True,1.0,440.0,...,2.0,1610612761,1610612761,1610612754,Pacers,Hornets,1610612754,1610612766,1610612766,1610612754
524,0022500268,2025-11-22,Hornets,Clippers,True,False,False,False,2.0,428.0,...,3.0,1610612754,1610612754,1610612766,Hornets,Clippers,1610612766,1610612746,1610612766,1610612746
525,0022500276,2025-11-23,Hornets,Hawks,False,True,True,NaN,0.0,227.0,...,1.0,1610612746,1610612766,1610612737,Hawks,Hornets,1610612737,1610612766,1610612766,1610612737

In [8]:
traveler.get_season_schedule(season_str=season_str, remove_gametypes=None)
a = traveler.schedules['raw'][season_str]
a.head(2)

,leagueId,seasonYear,gameDate,gameId,gameCode,gameStatus,gameStatusText,gameSequence,gameDateEst,gameTimeEst,...,awayOttBroadcasters_broadcasterMedia,awayOttBroadcasters_broadcasterId,awayOttBroadcasters_broadcasterDisplay,awayOttBroadcasters_broadcasterAbbreviation,awayOttBroadcasters_broadcasterDescription,awayOttBroadcasters_tapeDelayComments,awayOttBroadcasters_broadcasterVideoLink,awayOttBroadcasters_broadcasterTeamId,awayOttBroadcasters_broadcasterRanking,awayOttBroadcasters_localizationRegion
0,00,2025-26,10/02/2025 00:00:00,0012500008,20251002/PHINYK,3,Final,1,2025-10-02T00:00:00Z,1900-01-01T12:00:00Z,...,None,NaN,None,None,None,None,None,NaN,None,None
1,00,2025-26,10/03/2025 00:00:00,0012500001,20251003/PHXLAL,3,Final,2,2025-10-03T00:00:00Z,1900-01-01T22:00:00Z,...,ott,1001033.0,Suns+,DTC-PHX,,,,1.610613e+09,None,

In [9]:
b = a[(a['homeTeam_teamName'] == 'Celtics') | (a['awayTeam_teamName'] == 'Celtics')].sort_values('gameDate')

In [10]:
b

,leagueId,seasonYear,gameDate,gameId,gameCode,gameStatus,gameStatusText,gameSequence,gameDateEst,gameTimeEst,...,awayOttBroadcasters_broadcasterMedia,awayOttBroadcasters_broadcasterId,awayOttBroadcasters_broadcasterDisplay,awayOttBroadcasters_broadcasterAbbreviation,awayOttBroadcasters_broadcasterDescription,awayOttBroadcasters_tapeDelayComments,awayOttBroadcasters_broadcasterVideoLink,awayOttBroadcasters_broadcasterTeamId,awayOttBroadcasters_broadcasterRanking,awayOttBroadcasters_localizationRegion
547,00,2025-26,01/01/2026 00:00:00,0022500474,20260101/BOSSAC,1,10:00 pm ET,4,2026-01-01T00:00:00Z,1900-01-01T22:00:00Z,...,None,NaN,None,None,None,None,None,NaN,None,None
566,00,2025-26,01/03/2026 00:00:00,0022500493,20260103/BOSLAC,1,10:30 pm ET,8,2026-01-03T00:00:00Z,1900-01-01T22:30:00Z,...,None,NaN,None,None,None,None,None,NaN,None,None
576,00,2025-26,01/05/2026 00:00:00,0022500503,20260105/CHIBOS,1,7:30 pm ET,2,2026-01-05T00:00:00Z,1900-01-01T19:30:00Z,...,None,NaN,None,None,None,None,None,NaN,None,None
593,00,2025-26,01/07/2026 00:00:00,0022500520,20260107/DENBOS,1,7:30 pm ET,5,2026-01-07T00:00:00Z,1900-01-01T19:30:00Z,...,None,NaN,None,None,None,None,None,NaN,None,None
605,00,2025-26,01/09/2026 00:00:00,0022500532,20260109/TORBOS,1,7:00 pm ET,1,2026-01-09T00:00:00Z,1900-01-01T19:00:00Z,...,None,NaN,None,None,None,None,None,NaN,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456,00,2025-26,12/20/2025 00:00:00,0022500388,20251220/BOSTOR,1,7:00 pm ET,3,2025-12-20T00:00:00Z,1900-01-01T19:00:00Z,...,None,NaN,None,None,None,None,None,NaN,None,None
471,00,2025-26,12/22/2025 00:00:00,0022500403,20251222/INDBOS,1,7:30 pm ET,2,2025-12-22T00:00:00Z,1900-01-01T19:30:00Z,...,None,NaN,None,None,None,None,None,NaN,None,None
499,00,2025-26,12/26/2025 00:00:00,0022500426,20251226/BOSIND,1,7:30 pm ET,4,2025-12-26T00:00:00Z,1900-01-01T19:30:00Z,...,None,NaN,None,None,None,None,None,NaN,None,None
517,00,2025-26,12/28/2025 00:00:00,0022500444,20251228/BOSPOR,1,6:00 pm ET,4,2025-12-28T00:00:00Z,1900-01-01T18:00:00Z,...,None,NaN,None,None,None,None,None,NaN,None,None
532,00,2025-26,12/30/2025 00:00:00,0022500459,20251230/BOSUTA,1,9:00 pm ET,2,2025-12-30T00:00:00Z,1900-01-01T21:00:00Z,...,None,NaN,None,None,None,None,None,NaN,None,None

# historical research

### process data

In [ ]:
"""
It looks like the first season available in ScheduleLeagueV2 is 2017-18

 *********** COVID ************
The COVID season was 2019-2020. 
The last regular games was 3/10/2020
The bubble started on 7/30/20
The bubble ended on 10/11/20

The next season started 12/22/20
 ******************************
"""

import pandas as pd
import numpy as np
import time

covid_season = '2019-20'
covid_stop = '2020-03-11'
covid_bubble_start = '2020-07-30'
covid_bubble_end = '2020-10-11'
season_start_post_covid = '2020-12-22'

all_star_breaks = {
    '2017-18':{
        'start':'2018-02-16',
        'end':'2018-02-22',
    }, 
    '2018-19':{
        'start':'2019-02-15',
        'end':'2019-02-20'
    }, 
    '2019-20':{
        'start':'2020-02-14',
        'end':'2020-02-19'
    }, 
    '2020-21':{
        'start':'2021-03-05',
        'end':'2021-03-09'
    }, 
    '2021-22':{
        'start':'2022-02-18',
        'end':'2022-02-23'
    }, 
    '2022-23':{
        'start':'2023-02-17',
        'end':'2023-02-22'
    },
    '2023-24':{
        'start':'2024-02-16',
        'end':'2024-02-21'
    },
    '2024-25':{
        'start':'2025-02-14',
        'end':'2025-02-19'
    },
    '2025-26':{
        'start':'2026-02-13',
        'end':'2026-02-18'
    },
}


season_strs = [
    '2017-18', '2018-19', '2019-20', '2020-21', '2021-22', '2022-23', 
    '2023-24', '2024-25'
]

##### importing custom modules from the projects folder
import sys
from pathlib import Path
# Start at current working directory
current = Path.cwd()
# Walk up the tree until config.py is found or root is reached
for parent in [current] + list(current.parents):
    config_path = parent / "config.py"
    if config_path.exists():
        sys.path.append(str(parent))
        import config # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 
        break
else:
    raise FileNotFoundError("config.py not found in any parent directories")

import scripts.functions.NBAteamSeasonTravel as travel
import scripts.functions.NBAhelperfunctions as hf

traveler = travel.seasonTeamTravelDistanceCalculator()
# access csv that has calculated distances from arena to arena
traveler.get_arena_distances()

# pull in requested seasons
for i in season_strs:

    traveler.get_season_schedule(
        season_str=i, 
        remove_gametypes = ['001', '003', '004', '005', '006']  # filters down to only regular season using ['001', '003', '004', '005', '006']. None or empty will provide full schedules
    )
    time.sleep(2)
    print(i, 'retrieved...')

2017-18 retrieved...
2018-19 retrieved...
2019-20 retrieved...
2020-21 retrieved...
2021-22 retrieved...
2022-23 retrieved...
2023-24 retrieved...
2024-25 retrieved...
6601 games returned...

In [87]:
traveler.all_star_breaks = {
    '2017-18':{
        'start':'2018-02-16',
        'end':'2018-02-21',
    }, 
    '2018-19':{
        'start':'2019-02-15',
        'end':'2019-02-20'
    }, 
    '2019-20':{
        'start':'2020-02-14',
        'end':'2020-02-19'
    }, 
    '2020-21':{
        'start':'2021-03-05',
        'end':'2021-03-09'
    }, 
    '2021-22':{
        'start':'2022-02-18',
        'end':'2022-02-23'
    }, 
    '2022-23':{
        'start':'2023-02-17',
        'end':'2023-02-22'
    },
    '2023-24':{
        'start':'2024-02-16',
        'end':'2024-02-21'
    },
    '2024-25':{
        'start':'2025-02-14',
        'end':'2025-02-19'
    },
    '2025-26':{
        'start':'2026-02-13',
        'end':'2026-02-18'
    },
}

In [103]:

# process the data - adds travel calcs, days rest, road trip calcs
# as well as odds for data
traveler.process_historical_schedules()
df = traveler.schedules['historical']

6601 games returned...

In [104]:
# remove games that don't have odds data
df = df[df['total'].notna()]
df.shape

(12810, 48)

In [105]:
# only records for the away teams are kept since this is looking at road trip performance
d = df[~df['home']]
d.shape

(6405, 48)

In [106]:
d.loc[:,'homeFav'] = d['homeSpread'] < 0

d.loc[:,'totalScored'] = d['homeTeam_score'] + d['awayTeam_score']


d.loc[:,'awayDelta'] = d['awayTeam_score'] - d['homeTeam_score']
d.loc[:,'awayAts'] = d['awayDelta'] + d['awaySpread']

d.loc[:,'homeImpliedWinProb'] = hf.convert_ameri_odds_to_probability(d['homeMoneyline'])
d.loc[:,'awayImpliedWinProb'] = hf.convert_ameri_odds_to_probability(d['awayMoneyline'])
d.loc[:,'impTotalProb'] = d['homeImpliedWinProb'] + d['awayImpliedWinProb']

d.loc[:,'homeWin'] = d['homeTeam_score'] > d['awayTeam_score']
d.loc[:,'homeAtsWin'] = d['awayAts'] < 0
d.loc[:,'awayWin'] = d['awayTeam_score'] > d['homeTeam_score']
d.loc[:,'awayAtsWin'] = d['awayAts'] > 0
d.loc[:,'overTotal'] = d['totalScored'] > d['total']
d.loc[:,'underTotal'] = ~d['overTotal']

C:\Users\jrbrz\AppData\Local\Temp\ipykernel_7944\4030566996.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.loc[:,'homeFav'] = d['homeSpread'] < 0
C:\Users\jrbrz\AppData\Local\Temp\ipykernel_7944\4030566996.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.loc[:,'totalScored'] = d['homeTeam_score'] + d['awayTeam_score']
C:\Users\jrbrz\AppData\Local\Temp\ipykernel_7944\4030566996.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.loc[:,'awayDelta'] = d['awayTeam_score'] - d['homeTeam_score']
C:\Users\jrbrz\AppData\Local\Temp\ipykernel_7944\4030566996.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.loc[:,'awayAts'] = d['awayDelta'] + d['awaySpread']
C:\Users\jrbrz\AppData\Local\Temp\ipykernel_7944\4030566996.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.loc[:,'homeImpliedWinProb'] = hf.convert_ameri_odds_to_probability(d['homeMoneyline'])
C:\Users\jrbrz\AppData\Local\Temp\ipykernel_7944\4030566996.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.loc[:,'awayImpliedWinProb'] = hf.convert_ameri_odds_to_probability(d['awayMoneyline'])
C:\Users\jrbrz\AppData\Local\Temp\ipykernel_7944\4030566996.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.loc[:,'impTotalProb'] = d['homeImpliedWinProb'] + d['awayImpliedWinProb']
C:\Users\jrbrz\AppData\Local\Temp\ipykernel_7944\4030566996.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.loc[:,'homeWin'] = d['homeTeam_score'] > d['awayTeam_score']
C:\Users\jrbrz\AppData\Local\Temp\ipykernel_7944\4030566996.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.loc[:,'homeAtsWin'] = d['awayAts'] < 0
C:\Users\jrbrz\AppData\Local\Temp\ipykernel_7944\4030566996.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.loc[:,'awayWin'] = d['awayTeam_score'] > d['homeTeam_score']
C:\Users\jrbrz\AppData\Local\Temp\ipykernel_7944\4030566996.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.loc[:,'awayAtsWin'] = d['awayAts'] > 0
C:\Users\jrbrz\AppData\Local\Temp\ipykernel_7944\4030566996.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.loc[:,'overTotal'] = d['totalScored'] > d['total']
C:\Users\jrbrz\AppData\Local\Temp\ipykernel_7944\4030566996.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d.loc[:,'underTotal'] = ~d['overTotal']

In [107]:
d.to_csv(config.DATA_DIR / 'historical game lines/2008_2023_teamGameOdds.csv', index = False)

### analyze

In [108]:
import pandas as pd
import numpy as np

##### importing custom modules from the projects folder
import sys
from pathlib import Path
# Start at current working directory
current = Path.cwd()
# Walk up the tree until config.py is found or root is reached
for parent in [current] + list(current.parents):
    config_path = parent / "config.py"
    if config_path.exists():
        sys.path.append(str(parent))
        import config # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 
        break
else:
    raise FileNotFoundError("config.py not found in any parent directories")

import scripts.functions.NBAhelperfunctions as hf

In [109]:
filepath = config.DATA_DIR / 'historical game lines/2008_2023_teamGameOdds.csv'
df = pd.read_csv(filepath)
total_games = df.shape[0]

In [110]:
df

,gameId,gameDate,seasonYear,weekNumber,day,monthNum,win,team,opp,homeTeam_score,...,awayAts,homeImpliedWinProb,awayImpliedWinProb,impTotalProb,homeWin,homeAtsWin,awayWin,awayAtsWin,overTotal,underTotal
0,21700009,2017-10-18,2017-18,1,Wed,10,True,Hawks,Mavericks,111,...,11.5,0.706,0.345,1.051,False,False,True,True,True,False
1,21700017,2017-10-20,2017-18,1,Fri,10,False,Hawks,Hornets,109,...,-13.5,0.655,0.385,1.040,True,True,False,False,False,True
2,21700038,2017-10-22,2017-18,1,Sun,10,False,Hawks,Nets,116,...,-11.0,0.535,0.512,1.047,True,True,False,False,False,True
3,21700042,2017-10-23,2017-18,2,Mon,10,False,Hawks,Heat,104,...,-0.5,0.875,0.167,1.042,True,True,False,False,False,True
4,21700065,2017-10-26,2017-18,2,Thu,10,False,Hawks,Bulls,91,...,-3.0,0.565,0.476,1.041,True,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6400,22200513,2022-12-27,2022-23,11,Tue,12,False,Hornets,Warriors,110,...,0.0,0.655,0.370,1.025,True,False,False,False,False,True
6401,22200583,2023-01-06,2022-23,12,Fri,1,True,Hornets,Bucks,109,...,39.0,0.821,0.208,1.029,False,False,True,True,True,False
6402,22200598,2023-01-08,2022-23,12,Sun,1,False,Hornets,Pacers,116,...,0.5,0.688,0.345,1.033,True,False,False,True,False,True
6403,22200613,2023-01-10,2022-23,13,Tue,1,False,Hornets,Raptors,132,...,-4.5,0.750,0.286,1.036,True,True,False,False,True,False
6404,22200629,2023-01-12,2022-23,13,Thu,1,False,Hornets,Raptors,124,...,-2.5,0.756,0.278,1.034,True,True,False,False,True,False

In [117]:
a = df.groupby('cum_days_road_trip').agg(
    games = ('gameId', 'nunique'),
    aWinTot = ('awayWin', 'sum'),
    aAtsWinTot = ('awayAtsWin', 'sum')

).round(1)

a['mlWPct'] = a['aWinTot'] / a['games'] * 100
a['atsWPct'] = a['aAtsWinTot'] / a['games'] * 100
a.round(2)

                    games  aWinTot  aAtsWinTot  mlWPct  atsWPct
cum_days_road_trip
0.0                    73       36          42   49.32    57.53
1.0                  2859     1241        1424   43.41    49.81
2.0                   435      175         223   40.23    51.26
3.0                  1059      470         518   44.38    48.91
4.0                   548      227         272   41.42    49.64
5.0                   458      199         210   43.45    45.85
6.0                   368      162         188   44.02    51.09
7.0                   206       91         109   44.17    52.91
8.0                   169       69          84   40.83    49.70
9.0                    99       44          50   44.44    50.51
10.0                   69       29          35   42.03    50.72
11.0                   29       12          12   41.38    41.38
12.0                   18       10          11   55.56    61.11
13.0                   11        6           7   54.55    63.64
14.0                    3        3           3  100.00   100.00
16.0                    1        0           0    0.00     0.00

In [99]:
df[df['days_rest'] > 7]

,gameId,gameDate,seasonYear,weekNumber,day,monthNum,win,team,opp,homeTeam_score,...,awayAts,homeImpliedWinProb,awayImpliedWinProb,impTotalProb,homeWin,homeAtsWin,awayWin,awayAtsWin,overTotal,underTotal
29,21700874,2018-02-23,2017-18,19,Fri,2,False,Hawks,Pacers,116,...,-16.0,0.762,0.282,1.044,True,True,False,False,False,True
68,21700873,2018-02-23,2017-18,19,Fri,2,True,Celtics,Pistons,98,...,10.0,0.465,0.574,1.039,False,False,True,True,False,True
233,21700883,2018-02-23,2017-18,19,Fri,2,False,Mavericks,Lakers,124,...,-17.5,0.661,0.377,1.038,True,True,False,False,True,False
483,21700879,2018-02-23,2017-18,19,Fri,2,False,Heat,Pelicans,124,...,1.0,0.574,0.465,1.039,True,False,False,True,True,False
850,21700882,2018-02-23,2017-18,19,Fri,2,True,Trail Blazers,Jazz,81,...,23.5,0.655,0.385,1.040,False,False,True,True,False,True
933,21700880,2018-02-23,2017-18,19,Fri,2,False,Spurs,Nuggets,122,...,1.0,0.630,0.408,1.038,True,False,False,True,True,False
1423,21800875,2019-02-22,2018-19,19,Fri,2,True,Bulls,Magic,109,...,9.0,0.792,0.256,1.048,False,False,True,True,True,False
1504,21800880,2019-02-22,2018-19,19,Fri,2,True,Nuggets,Mavericks,104,...,3.0,0.278,0.767,1.045,False,False,True,True,False,True
1630,21800879,2019-02-22,2018-19,19,Fri,2,True,Clippers,Grizzlies,106,...,3.0,0.426,0.608,1.034,False,False,True,True,True,False
1791,21800878,2019-02-22,2018-19,19,Fri,2,True,Timberwolves,Knicks,104,...,7.5,0.408,0.630,1.038,False,False,True,True,False,True
2162,21800876,2019-02-22,2018-19,19,Fri,2,False,Spurs,Raptors,120,...,5.0,0.800,0.250,1.050,True,False,False,True,True,False
2284,21800881,2019-02-22,2018-19,19,Fri,2,False,Jazz,Thunder,148,...,3.5,0.667,0.370,1.037,True,False,False,True,True,False
2367,21800873,2019-02-22,2018-19,19,Fri,2,False,Wizards,Hornets,123,...,-8.0,0.688,0.357,1.045,True,True,False,False,True,False
2404,21800877,2019-02-22,2018-19,19,Fri,2,True,Pistons,Hawks,122,...,-1.5,0.385,0.655,1.040,False,True,True,False,True,False
2550,21900827,2020-02-21,2019-20,18,Fri,2,True,Cavaliers,Wizards,108,...,11.5,0.718,0.328,1.046,False,False,True,True,False,True
2643,21900826,2020-02-21,2019-20,18,Fri,2,True,Mavericks,Magic,106,...,11.5,0.385,0.655,1.040,False,False,True,True,True,False
2677,21900831,2020-02-21,2019-20,18,Fri,2,False,Nuggets,Thunder,113,...,-10.5,0.565,0.476,1.041,True,True,False,False,False,True
2740,21900825,2020-02-20,2019-20,18,Thu,2,True,Rockets,Warriors,105,...,20.0,0.211,0.833,1.044,False,False,True,True,True,False
3033,21900828,2020-02-21,2019-20,18,Fri,2,True,Pacers,Knicks,98,...,1.5,0.299,0.744,1.043,False,False,True,True,False,True
3100,21900829,2020-02-21,2019-20,18,Fri,2,False,Suns,Raptors,118,...,-9.0,0.792,0.256,1.048,True,True,False,False,False,True
3199,21900832,2020-02-21,2019-20,18,Fri,2,True,Spurs,Jazz,104,...,16.0,0.750,0.294,1.044,False,False,True,True,False,True
3520,22000581,2021-03-12,2020-21,12,Fri,3,False,Cavaliers,Pelicans,116,...,-27.5,0.737,0.294,1.031,True,True,False,False,False,True
4235,22000495,2021-02-24,2020-21,10,Wed,2,False,Spurs,Thunder,102,...,-3.0,0.524,0.524,1.048,True,True,False,False,False,True
4372,22000304,2021-01-30,2020-21,6,Sat,1,True,Grizzlies,Spurs,112,...,20.5,0.630,0.400,1.030,False,False,True,True,True,False
4408,22000253,2021-01-24,2020-21,5,Sun,1,False,Wizards,Spurs,121,...,-14.5,0.706,0.333,1.039,True,True,False,False,False,True
4624,22100889,2022-02-24,2021-22,19,Thu,2,False,Cavaliers,Pistons,106,...,-8.5,0.345,0.688,1.033,True,True,False,False,False,True
5443,22100899,2022-02-25,2021-22,19,Fri,2,True,Spurs,Wizards,153,...,0.5,0.417,0.615,1.032,False,False,True,True,True,False
5523,22100896,2022-02-25,2021-22,19,Fri,2,False,Raptors,Hornets,125,...,-34.0,0.465,0.574,1.039,True,True,False,False,False,True